"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os # Este módulo se utiliza para manejar rutas de archivos y directorios, aunque en este caso no es estrictamente necesario, ya que estamos utilizando pathlib para manejar las rutas. Sin embargo, es común importarlo en proyectos Django para casos donde se necesite manipular rutas de archivos de manera más tradicional.
import dj_database_url # Este módulo se utiliza para configurar la base de datos en producción, permitiendo leer la configuración de la base de datos desde una variable de entorno. Aunque en este caso estamos utilizando SQLite para desarrollo, como ya sabemos, en producción es recomendable utilizar una base de datos más robusta como PostgreSQL, y dj_database_url facilita esta configuración.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', default='your secret key') # Acá se obtiene la clave secreta de las variables de entorno, lo que es una buena práctica para mantener la seguridad. Si no se encuentra la variable de entorno, se utiliza un valor por defecto (que no debe ser utilizado en producción). Debemos asegurarnos de establecer la variable de entorno.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ # Esta línea verifica si la aplicación se está ejecutando en Render (un servicio de hosting) al comprobar la presencia de la variable de entorno 'RENDER'. Si esta variable no está presente, se asume que estamos en un entorno de desarrollo y se habilita el modo de depuración (DEBUG = True). En producción, esta variable debería estar presente, lo que hará que DEBUG sea False, aumentando así la seguridad de la aplicación.

ALLOWED_HOSTS = []

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME) # Esto agrega el hostname externo proporcionado por Render a la lista de hosts permitidos (ALLOWED_HOSTS), lo que es necesario para que la aplicación pueda responder a solicitudes en ese entorno de producción. Es importante configurar esto correctamente para evitar problemas de seguridad relacionados con hosts no autorizados.

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks'
]

# pip install 'whitenoise[brotli]' para servir archivos estáticos en producción. Al instalar WhiteNoise, se puede configurar el middleware para que sirva los archivos estáticos directamente desde la aplicación, lo que simplifica la configuración y mejora el rendimiento.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Este middleware se encarga de servir los archivos estáticos en producción utilizando WhiteNoise. Es importante agregarlo después del SecurityMiddleware para asegurarse de que los archivos estáticos se sirvan de manera segura.
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#  pip install dj-database-url psycopg2-binary para manejar la base de datos en producción. Aunque en este caso estamos utilizando SQLite para desarrollo, en producción, es recomendable utilizar una base de datos más robusta como PostgreSQL, y para eso se puede configurar utilizando dj-database-url para leer la configuración de la base de datos desde una variable de entorno.

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:postgres@localhost:5432/mysite',
        conn_max_age=600
    )
} # Esta configuración utiliza dj_database_url para configurar la base de datos. La URL de conexión a la base de datos se puede proporcionar a través de una variable de entorno, lo que facilita la configuración en diferentes entornos sin tener que cambiar el código.


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # staticfiles es el directorio donde se recopilarán todos los archivos estáticos en producción. Para crearlo, se debe ejecutar el comando 'python manage.py collectstatic', que recopilará todos los archivos estáticos de las aplicaciones y los colocará en este directorio. Esto es necesario para que WhiteNoise pueda servir los archivos estáticos de manera eficiente en producción.
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' # Esta configuración indica que en producción, los archivos estáticos se almacenarán en el directorio 'staticfiles' dentro del BASE_DIR, y se utilizará el almacenamiento de WhiteNoise para servir los archivos estáticos de manera eficiente, incluyendo la compresión y la gestión de versiones para mejorar el rendimiento.


LOGIN_URL = 'signin'